name: Update Rules From Sublime Repo

on:
    schedule:
      - cron:  '5 1,7,13,19 * * *'
    workflow_dispatch: {}
    
jobs:
    tests:
        name: Run Rule Validation
        runs-on: ubuntu-20.04
        permissions:
            contents: write
            checks: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  depth: 0

            - uses: actions/setup-python@v4
              with:
                  python-version: '3.10'


            - name: Synchronize With Master Sublime Repo
              run: |
                  git remote add sublime https://github.com/sublime-security/sublime-rules.git
                  git fetch all
                  git merge -X ours sublime/main -m "Updating from sublime"

                  pip install -r scripts/change-url-to-mimecast/requirements.txt
                  python scripts/change-url-to-mimecast/main.py
                  git add mimecast-detection-rules/*

                  git config --global user.name Mimecast update bot'
                  git config --global user.email 'hello@sublimesecurity.com'
                  
                  git commit --allow-empty -m "updating rules"
                  git push

